name: "Liter Check"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  license-check:
    name: "Python linter"
    runs-on: "ubuntu-latest"

    container:
      image: "hanyuu/python:wps"

    steps:
      - name: "Checkout code"

      - name: "Run linter"
        run: "flake8 app/"

      - name: "Handle failure (optional)"
        if: failure()
        run: "echo \"Linter check failed! Please review errors\""
